name: Build and Publish Nginx Image

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:

      - name: Checkout komet repository
        uses: actions/checkout@v3
        with:
          repository: 'ikmdev/komet'

      - name: Upload Docker compose file
        uses: actions/upload-artifact@v4
        with:
          name: docker-compose
          path: docker-compose.yml
        
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download docker-compose file
        uses: actions/download-artifact@v4
        with:
          name: docker-compose

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build nginx image and tag
        run: |
          docker compose -f docker-compose.yml build nginx

      - name: Push nginx image
        run: docker compose -f docker-compose.yml push nginx
