name: Build and Publish Nginx Image

on:
 push:
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    needs: tests
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build nginx image and tag
      run: | 
         docker compose -f docker-compose.yml build nginx
         

      #  docker tag nginx ${{ secrets.DOCKER_USERNAME }}/nginx:1.26.3

    - name: Push nginx image
      run: docker compose -f docker-compose.yml push nginx

  tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: build docker-compose
        run:  docker compose up -d 

      - name: curl localhost:8080
        run: curl http://localhost:8080