name: Build and Publish Static Website

on:
  workflow_dispatch:
  push:
   tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
        
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker Image
        run:  docker build -t ${{ secrets.DOCKER_USERNAME }}/ikmdev-site:${{ github.ref_name }} .
          

      - name: Push docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ikmdev-site:${{ github.ref_name }}



 
